### ISSUE TITLE
Failed to apply preset

### ISSUE THREAD

**Issue by Coffee00** [Stekeblad/Stekeblads-Video-Uploader#30] opened 2021-08-05 21:04 UTC
Hi, @Stekeblad!
When I try to use preset for video I get the error "Failed to apply preset to the file..." with this code:

`Failed to apply preset to the file "testvideo.mp4" 
Here is the error details: 
---------------------------------------— 
null 
---------------------------------------— 
java.util.ConcurrentModificationException 
 at java.util.WeakHashMap$HashIterator.nextEntry(Unknown Source) 
 at java.util.WeakHashMap$EntryIterator.next(Unknown Source) 
 at java.util.WeakHashMap$EntryIterator.next(Unknown Source) 
 at com.sun.javafx.css.StyleManager.forget(Unknown Source) 
 at javafx.scene.Parent.scenesChanged(Unknown Source) 
 at javafx.scene.Node.invalidatedScenes(Unknown Source) 
 at javafx.scene.Node.setScenes(Unknown Source) 
 at javafx.scene.Parent$2.onProposedChange(Unknown Source) 
 at com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source) 
 at com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source) 
 at javafx.scene.control.Tooltip.<init>(Unknown Source) 
 at io.github.stekeblad.videouploader.youtube.VideoInformationBase.makeVideoBasePane(VideoInformationBase.java:758) 
 at io.github.stekeblad.videouploader.youtube.VideoInformationBase.<init>(VideoInformationBase.java:404) 
 at io.github.stekeblad.videouploader.youtube.VideoUpload.<init>(VideoUpload.java:123) 
 at io.github.stekeblad.videouploader.youtube.VideoUpload$Builder.build(VideoUpload.java:245) 
 at io.github.stekeblad.videouploader.utils.background.PresetApplicator.apply(PresetApplicator.java:173) 
 at io.github.stekeblad.videouploader.utils.background.PresetApplicator.access$000(PresetApplicator.java:21) 
 at io.github.stekeblad.videouploader.utils.background.PresetApplicator$1.call(PresetApplicator.java:95) 
 at io.github.stekeblad.videouploader.utils.background.PresetApplicator$1.call(PresetApplicator.java:89) 
 at javafx.concurrent.Task$TaskCallable.call(Unknown Source) 
 at java.util.concurrent.FutureTask.run(Unknown Source) 
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
 at java.util.concurrent.FutureTask.run(Unknown Source) 
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
 at java.lang.Thread.run(Unknown Source)
[Ссылка]
futuretask.run
http://java.util.concurrent.FutureTask.run`

But even if the preset is applied I get this error:

`Sorry, something went wrong! 
Here is the error details: 
---------------------------------------— 
null 
---------------------------------------— 
java.lang.NullPointerException 
 at com.sun.javafx.css.StyleManager.findMatchingStyles(Unknown Source) 
 at javafx.scene.CssStyleHelper.createStyleHelper(Unknown Source) 
 at javafx.scene.Node.reapplyCss(Unknown Source) 
 at javafx.scene.Node.impl_reapplyCSS(Unknown Source) 
 at javafx.scene.Node.invalidatedScenes(Unknown Source) 
 at javafx.scene.Node.setScenes(Unknown Source) 
 at javafx.scene.Parent.scenesChanged(Unknown Source) 
 at javafx.scene.Node.invalidatedScenes(Unknown Source) 
 at javafx.scene.Node.setScenes(Unknown Source) 
 at javafx.scene.Parent$1.onChanged(Unknown Source) 
 at com.sun.javafx.collections.TrackableObservableList.lambda$new$19(Unknown Source) 
 at com.sun.javafx.collections.TrackableObservableList$$Lambda$54/144939863.onChanged(Unknown Source) 
 at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source) 
 at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source) 
 at javafx.collections.ObservableListBase.fireChange(Unknown Source) 
 at javafx.collections.ListChangeBuilder.commit(Unknown Source) 
 at javafx.collections.ListChangeBuilder.endChange(Unknown Source) 
 at javafx.collections.ObservableListBase.endChange(Unknown Source) 
 at javafx.collections.ModifiableObservableListBase.setAll(Unknown Source) 
 at com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source) 
 at com.sun.javafx.collections.VetoableListDecorator.setAll(Unknown Source) 
 at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(Unknown Source) 
 at com.sun.javafx.scene.control.skin.LabeledSkinBase.<init>(Unknown Source) 
 at com.sun.javafx.scene.control.skin.CellSkinBase.<init>(Unknown Source) 
 at com.sun.javafx.scene.control.skin.ListCellSkin.<init>(Unknown Source) 
 at javafx.scene.control.ListCell.createDefaultSkin(Unknown Source) 
 at javafx.scene.control.Control.impl_processCSS(Unknown Source) 
 at javafx.scene.Node.processCSS(Unknown Source) 
 at javafx.scene.Node.applyCss(Unknown Source) 
 at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(Unknown Source) 
 at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(Unknown Source) 
 at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(Unknown Source) 
 at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(Unknown Source) 
 at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(Unknown Source) 
 at javafx.scene.Parent.layout(Unknown Source) 
 at javafx.scene.Parent.layout(Unknown Source) 
 at javafx.scene.Parent.layout(Unknown Source) 
 at javafx.scene.Scene.doLayoutPass(Unknown Source) 
 at javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source) 
 at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Unknown Source) 
 at com.sun.javafx.tk.Toolkit$$Lambda$288/310315715.run(Unknown Source) 
 at java.security.AccessController.doPrivileged(Native Method) 
 at com.sun.javafx.tk.Toolkit.runPulse(Unknown Source) 
 at com.sun.javafx.tk.Toolkit.firePulse(Unknown Source) 
 at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source) 
 at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source) 
 at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(Unknown Source) 
 at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$40/443776506.run(Unknown Source) 
 at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) 
 at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) 
 at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source) 
 at com.sun.glass.ui.win.WinApplication$$Lambda$36/1963387170.run(Unknown Source) 
 at java.lang.Thread.run(Unknown Source)`

**Comment by Stekeblad** [comment] 2021-08-06 07:46
Hi @Coffee00

Did this happen only once or are you able to recreate the errors? If you can recreate them then can you please describe the steps?

**Comment by Coffee00** [comment] 2021-08-06 09:55
These errors occur constantly when trying to apply a preset to a video. Here are the steps that lead to errors:
1. Select videos with "pick files"
2. Select a preset with "select a preset"
3. Apply preset

I tried to fix this problem by deleting data of uploader and redownload application but this didn't work

**Comment by Stekeblad** [comment] 2021-08-08 15:12
I have made some investigation and I can not recreate the errors.

I have a long shot guess of what can be the problem in the first error but currently not the time to implement it. For the second error, if its not a consequence of the first one then I don't have a clue of where the problem is.

**Comment by Coffee00** [comment] 2021-08-09 12:44
Thanks for your answer, @Stekeblad 

I found a solution to the problem. 
All errors occurred due to the old version of Java. After upgrading to version 301, everything started working.

**Comment by Stekeblad** [comment] 2021-08-09 15:43
Fantastic!

I am closing this issue

**Closed by Stekeblad** 2021-08-09 15:43 UTC

**Comment by saiif2018** [comment] 2021-08-09 21:39
Does youtube have daily limit of videos i can upload ? And what is it?

بتاريخ الاثنين، 9 أغسطس 2021، جاء من Stekeblad ***@***.***>:

**Comment by Stekeblad** [comment] 2021-08-10 04:28
Hi @saiif2018 

I do not apply a per-user limit (but YouTube may). There is a daily limit shared between all users that has been reached several times the last two weeks. I have a request to YouTube about increasing the limit and I am waiting for their response.
