### ISSUE TITLE
question

### ISSUE THREAD

**Issue by klimenko-fun** [Stekeblad/Stekeblads-Video-Uploader#24] opened 2021-05-23 16:51 UTC
How to contact you? I have some questions

**Comment by Stekeblad** [comment] 2021-05-23 17:00
If its something you can ask publicly and related to Stekeblads Video Uploader then here is the right place.

If its something that not anybody should know about then this is the first time I get this kind of question and I need to think how and where I want to handle them.

What are your questions @klimenko-fun?

**Comment by klimenko-fun** [comment] 2021-05-23 17:03
I have such a problem that when uploading videos through my api, YouTube blocks the video and puts private access on it. How to solve this problem? My project has been verified

**Comment by Stekeblad** [comment] 2021-05-23 17:16
If YouTube blocks your video I think you can see why in YouTube Studio (https://studio.youtube.com/channel/<your channel ID>/videos/upload) Maybe you are using copyright protected music?

**Comment by klimenko-fun** [comment] 2021-05-23 17:21
No, I am not violating any copyright. My video just gets into private access. When uploading a video manually, it downloads without issue. But when I start to load it via api it is blocked due to "conditions and rules" 
Check screen - https://prnt.sc/13b98cq

**Comment by Stekeblad** [comment] 2021-05-23 17:23
If you hover over terms and policies, do you get more information?

**Comment by klimenko-fun** [comment] 2021-05-23 17:25
https://prnt.sc/13b9ctv

**Comment by klimenko-fun** [comment] 2021-05-23 17:26
I read on the forum that maybe YouTube does not publish the video to the public because of an unverified api. But my api is verified and I don't understand why I get this error

**Comment by Stekeblad** [comment] 2021-05-23 17:26
![image](https://user-images.githubusercontent.com/12627375/119270395-c23f1980-bbfc-11eb-9f52-e9f207307ad7.png)

**Comment by klimenko-fun** [comment] 2021-05-23 17:28
![image](https://user-images.githubusercontent.com/84387284/119270443-6036e200-bc05-11eb-92cc-1f14669902d0.png)
![image](https://user-images.githubusercontent.com/84387284/119270450-662cc300-bc05-11eb-8c68-a845ee9820d9.png)

**Comment by Stekeblad** [comment] 2021-05-23 17:31
Sorry, I have no idea what the problem is.

If you try upload that same video at [https://www.youtube.com/upload](https://www.youtube.com/upload) will it still be forced to private by YouTube?

**Comment by klimenko-fun** [comment] 2021-05-23 17:32
I say that when I upload this video myself to YouTube, it is not blocked, and when I upload it via api, it is placed in private access

**Comment by klimenko-fun** [comment] 2021-05-23 17:33
It seems that YouTube has changed the rules about api and people will not be able to create their own api and load through it. YouTube will simply block the video and place it in private access.

**Comment by Stekeblad** [comment] 2021-05-23 17:35
I will try looking into it

**Comment by klimenko-fun** [comment] 2021-05-23 17:36
I have a question, have you verified your api?

**Comment by Stekeblad** [comment] 2021-05-23 17:38
Try uploading using version 1.4.3, the app is verified. It may have something to about using your own API key

**Comment by klimenko-fun** [comment] 2021-05-23 17:40
Yes, I use my api in your application, but my videos are placed in private access. Can you help me somehow?

**Comment by klimenko-fun** [comment] 2021-05-23 17:42
![image](https://user-images.githubusercontent.com/84387284/119270835-5c0bc400-bc07-11eb-877f-ece6c31085a6.png)

**Comment by Stekeblad** [comment] 2021-05-23 17:42
Version 1.4.3 uses my API, 1.4.4 requires your own API. You probably use 1.4.4, please try with 1.4.3

**Comment by klimenko-fun** [comment] 2021-05-23 17:43
This is how I want to upload videos via my api. After all, you are planning to disable your api soon

**Comment by Stekeblad** [comment] 2021-05-23 17:49
I will look into this

**Comment by klimenko-fun** [comment] 2021-05-23 18:26
How is it there?

**Comment by klimenko-fun** [comment] 2021-05-25 00:21
hey?

**Comment by Stekeblad** [comment] 2021-05-25 16:45
It looks like you may need to pass an audit by YouTube before being allowed to upload unlisted or public videos. It can be done using [this form](https://support.google.com/youtube/contact/yt_api_form). The option says "Audit Initiated by YouTube" but initiate the audit yourself.

Tip: The linked form is the same you use if you want to apply for a higher quota limit, in other words, increase the number of videos you are allowed to upload in a single day.

It became a bit more complicated than I wished for to use your own API key. One day I wish to be able use my API key again but there are a few problems I am stuck on and need to solve before that can happen..

**Comment by klimenko-fun** [comment] 2021-05-25 16:58
Maybe then you won't disable your api? It will be very difficult for people to approve their api

**Comment by Stekeblad** [comment] 2021-05-25 18:23
It was not an easy decision, but I can't leave the API available with the current issues. I understand it may be difficult for some users to set up their on API and I have not given up on being able to re-enable my API again. I hope you can understand.

**Comment by Stekeblad** [comment] 2021-06-02 19:33
After much investigating I think I will partially revert the 1.4.4 update. From what I can find I may not be doing more wrong then I first thought and instead more right then I knew. This is what will happen:
- The feature to use your own API key will stay, but it will not be required in 1.4.5
- Versions older than 1.4.4 will still stop working during the weekend 12-13 June
- 1.4.5 will be released during this weekend

**Closed** 2021-06-06 02:03 UTC
