### ISSUE TITLE
$(rawname) tag don't work

### ISSUE THREAD

**Issue by syllent** [Stekeblad/Stekeblads-Video-Uploader#16] opened 2020-06-10 18:53 UTC
Why did you remove the ability to put a title by the name of the file

**Comment by Stekeblad** [comment] 2020-06-11 04:13
I did not remove the support for tags, this is a bug. ( And a duplicate of issue #14 )
I hope to have an update that fixes all the tags ready this week.

**Closed** 2020-06-11 17:52 UTC
Labels: duplicate
